# Your workflow name.
name: Deploy to Render.

# Run workflow on every push to main branch.
on:
  push:
    branches: [main]

# Your workflows jobs.
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # Check-out your repository.
      - name: Checkout
        uses: actions/checkout@v2

### ⬇ IMPORTANT PART ⬇ ###

      - name: Build and Deploy to Render # Your custom step name
        uses: render-examples/render-deploy@v1.0.0 # GitHub action for Render
        with:
          # Your Render service name.
          service_name: ${{ secrets.RENDER_SERVICE_NAME }}

          # Your Render API key (set this as a secret in your GitHub repository).
          render_api_key: ${{ secrets.RENDER_API_KEY }}

          # (Optional) Specify the Dockerfile directory if not in the root.
          dockerfile_directory: ./

          # (Optional) Specify the Dockerfile name if different from default.
          dockerfile_name: Dockerfile

          # (Optional) Additional options for Docker build command.
          docker_options: "--no-cache"

### ⬆ IMPORTANT PART ⬆ ###

